<!-- Menu -->
<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
    <div class="logo menu_mm">
        <a href="#">Home</a>
    </div>
    <div class="search">
        <form action="#">
            <input type="search" class="header_search_input menu_mm" required="required" placeholder="Type to Search...">
            <img class="header_search_icon menu_mm" src="zend/public/images/search_2.png" alt="">
        </form>
    </div>
    <nav class="menu_nav">
        <ul class="menu_mm">
            <li class="menu_mm">
                <a href="index.html">home</a>
            </li>
            <li class="menu_mm">
                <a href="#">Fashion</a>
            </li>
            <li class="menu_mm">
                <a href="#">Gadgets</a>
            </li>
            <li class="menu_mm">
                <a href="#">Lifestyle</a>
            </li>
            <li class="menu_mm">
                <a href="#">Video</a>
            </li>
            <li class="menu_mm">
                <a href="contact.html">Contact</a>
            </li>
        </ul>
    </nav>
</div>

<!-- Home -->
<div class="home">
    <div class="home_background parallax-window" data-parallax="scroll" data-image-src="zend/public/images/category.jpg"></div>
</div>
<!-- Page Content -->

<div class="page_content">
    <div class="container">
        <div class="row row-lg-eq-height">
            <!-- Main Content -->
            <div class="col-lg-9">
                <div class="main_content">
                    <!-- Category -->
                    <div class="category">
                        <div class="section_panel d-flex flex-row align-items-center justify-content-start">
                            <div class="section_title">Don't Miss</div>
                            <div class="section_tags ml-auto">
                                <ul>
                                    <li class="active">
                                        <a href="category.html">all</a>
                                    </li>
                                    <li>
                                        <a href="category.html">style hunter</a>
                                    </li>
                                    <li>
                                        <a href="category.html">vogue</a>
                                    </li>
                                    <li>
                                        <a href="category.html">health & fitness</a>
                                    </li>
                                    <li>
                                        <a href="category.html">travel</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="section_panel_more">
                                <ul>
                                    <li>
                                        more
                                        <ul>
                                            <li>
                                                <a href="category.html">new look 2018</a>
                                            </li>
                                            <li>
                                                <a href="category.html">street fashion</a>
                                            </li>
                                            <li>
                                                <a href="category.html">business</a>
                                            </li>
                                            <li>
                                                <a href="category.html">recipes</a>
                                            </li>
                                            <li>
                                                <a href="category.html">sport</a>
                                            </li>
                                            <li>
                                                <a href="category.html">celebrities</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="section_content">
                            <div class="grid clearfix" style="display: flex;justify-content: space-between;">
                                <!-- Largest Card With Image -->
                                <div class="card card_largest_with_image grid-item">
                                    <img class="card-img-top" src="zend/public/images/post_1.jpg" alt="https://unsplash.com/@cjtagupa">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <a href="./post">How Did van Gogh’s Turbulent Mind Depict One of the Most Complex Concepts in
                                                Physics?</a>
                                        </div>
                                        <p class="card-text">Pick the yellow peach that looks like a sunset with its red, orange, and pink coat
                                            skin, peel it off with your teeth. Sink them into unripened...</p>
                                        <small class="post_meta">
                                            <a href="#">Sang</a>
                                            <span>Sep 29, 2017 at 9:48 am</span>
                                        </small>
                                    </div>
                                </div>
                            </div>
                            <div class="grid clearfix" style="display: flex;justify-content: space-between;">
                                <!-- Small Card With Image -->
                                <div class="card card_small_with_image grid-item">
                                    <img class="card-img-top" src="zend/public/images/post_22.jpg" alt="">
                                    <div class="card-body">
                                        <div class="card-title card-title-small">
                                            <a href="./post">How Did van Gogh’s Turbulent Mind Depict One of the Most Complex Concepts in
                                                Physics?</a>
                                        </div>
                                        <small class="post_meta">
                                            <a href="#">Katy Liu</a>
                                            <span>Sep 29, 2017 at 9:48 am</span>
                                        </small>
                                    </div>
                                </div>
                                <!-- Small Card With Image -->
                                <div class="card card_small_with_image grid-item">
                                    <img class="card-img-top" src="zend/public/images/post_19.jpg" alt="">
                                    <div class="card-body">
                                        <div class="card-title card-title-small">
                                            <a href="./post">How Did van Gogh’s Turbulent Mind Depict One of the Most Complex Concepts in
                                                Physics?</a>
                                        </div>
                                        <small class="post_meta">
                                            <a href="#">Katy Liu</a>
                                            <span>Sep 29, 2017 at 9:48 am</span>
                                        </small>
                                    </div>
                                </div>

                                <!-- Small Card With Image -->
                                <div class="card card_small_with_image grid-item">
                                    <img class="card-img-top" src="zend/public/images/post_21.jpg" alt="">
                                    <div class="card-body">
                                        <div class="card-title card-title-small">
                                            <a href="./post">How Did van Gogh’s Turbulent Mind Depict One of the Most Complex Concepts in
                                                Physics?</a>
                                        </div>
                                        <small class="post_meta">
                                            <a href="#">Katy Liu</a>
                                            <span>Sep 29, 2017 at 9:48 am</span>
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="load_more">
                    <div id="load_more" class="load_more_button text-center trans_200">Load More</div>
                </div>
            </div>

            <!-- Sidebar -->

            <div class="col-lg-3">
                <div class="sidebar">
                    <div class="sidebar_background"></div>

                    <!-- Top Stories -->

                    <div class="sidebar_section">
                        <div class="sidebar_title_container">
                            <div class="sidebar_title">Top Stories</div>
                            <div class="sidebar_slider_nav">
                                <div class="custom_nav_container sidebar_slider_nav_container">
                                    <div class="custom_prev custom_prev_top">
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="7px"
                                            height="12px" viewBox="0 0 7 12" enable-background="new 0 0 7 12" xml:space="preserve">
                                            <polyline fill="#bebebe" points="0,5.61 5.609,0 7,0 7,1.438 2.438,6 7,10.563 7,12 5.609,12 -0.002,6.39 " />
                                        </svg>
                                    </div>
                                    <ul id="custom_dots" class="custom_dots custom_dots_top">
                                        <li class="custom_dot custom_dot_top active">
                                            <span></span>
                                        </li>
                                        <li class="custom_dot custom_dot_top">
                                            <span></span>
                                        </li>
                                        <li class="custom_dot custom_dot_top">
                                            <span></span>
                                        </li>
                                    </ul>
                                    <div class="custom_next custom_next_top">
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="7px"
                                            height="12px" viewBox="0 0 7 12" enable-background="new 0 0 7 12" xml:space="preserve">
                                            <polyline fill="#bebebe" points="6.998,6.39 1.389,12 -0.002,12 -0.002,10.562 4.561,6 -0.002,1.438 -0.002,0 1.389,0 7,5.61 "
                                            />
                                        </svg>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="sidebar_section_content">

                            <!-- Top Stories Slider -->
                            <div class="sidebar_slider_container">
                                <div class="owl-carousel owl-theme sidebar_slider_top">

                                    <!-- Top Stories Slider Item -->
                                    <div class="owl-item">

                                        <!-- Sidebar Post -->
                                        <div class="side_post">
                                            <a href="./post">
                                                <div class="d-flex flex-row align-items-xl-center align-items-start justify-content-start">
                                                    <div class="side_post_image">
                                                        <div>
                                                            <img src="zend/public/images/top_1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="side_post_content">
                                                        <div class="side_post_title">How Did van Gogh’s Turbulent Mind</div>
                                                        <small class="post_meta">Katy Liu
                                                            <span>Sep 29</span>
                                                        </small>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <!-- Sidebar Post -->
                                        <div class="side_post">
                                            <a href="./post">
                                                <div class="d-flex flex-row align-items-xl-center align-items-start justify-content-start">
                                                    <div class="side_post_image">
                                                        <div>
                                                            <img src="zend/public/images/top_1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="side_post_content">
                                                        <div class="side_post_title">How Did van Gogh’s Turbulent Mind</div>
                                                        <small class="post_meta">Katy Liu
                                                            <span>Sep 29</span>
                                                        </small>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>

                                    <!-- Top Stories Slider Item -->
                                    <div class="owl-item">

                                        <!-- Sidebar Post -->
                                        <div class="side_post">
                                            <a href="./post">
                                                <div class="d-flex flex-row align-items-xl-center align-items-start justify-content-start">
                                                    <div class="side_post_image">
                                                        <div>
                                                            <img src="zend/public/images/top_1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="side_post_content">
                                                        <div class="side_post_title">How Did van Gogh’s Turbulent Mind</div>
                                                        <small class="post_meta">Katy Liu
                                                            <span>Sep 29</span>
                                                        </small>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>

                                    </div>

                                    <!-- Top Stories Slider Item -->
                                    <div class="owl-item">

                                        <!-- Sidebar Post -->
                                        <div class="side_post">
                                            <a href="./post">
                                                <div class="d-flex flex-row align-items-xl-center align-items-start justify-content-start">
                                                    <div class="side_post_image">
                                                        <div>
                                                            <img src="zend/public/images/top_1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="side_post_content">
                                                        <div class="side_post_title">How Did van Gogh’s Turbulent Mind</div>
                                                        <small class="post_meta">Katy Liu
                                                            <span>Sep 29</span>
                                                        </small>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Newest Videos -->
                    <div class="sidebar_section newest_videos">
                        <div class="sidebar_title_container">
                            <div class="sidebar_title">Newest Stories</div>
                            <div class="sidebar_slider_nav">
                                <div class="custom_nav_container sidebar_slider_nav_container">
                                    <div class="custom_prev custom_prev_vid">
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="7px"
                                            height="12px" viewBox="0 0 7 12" enable-background="new 0 0 7 12" xml:space="preserve">
                                            <polyline fill="#bebebe" points="0,5.61 5.609,0 7,0 7,1.438 2.438,6 7,10.563 7,12 5.609,12 -0.002,6.39 " />
                                        </svg>
                                    </div>
                                    <ul id="custom_dots" class="custom_dots custom_dots_vid">
                                        <li class="custom_dot custom_dot_vid active">
                                            <span></span>
                                        </li>
                                        <li class="custom_dot custom_dot_vid">
                                            <span></span>
                                        </li>
                                        <li class="custom_dot custom_dot_vid">
                                            <span></span>
                                        </li>
                                    </ul>
                                    <div class="custom_next custom_next_vid">
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="7px"
                                            height="12px" viewBox="0 0 7 12" enable-background="new 0 0 7 12" xml:space="preserve">
                                            <polyline fill="#bebebe" points="6.998,6.39 1.389,12 -0.002,12 -0.002,10.562 4.561,6 -0.002,1.438 -0.002,0 1.389,0 7,5.61 "
                                            />
                                        </svg>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="sidebar_section_content">

                            <!-- Sidebar Slider -->
                            <div class="sidebar_slider_container">
                                <div class="owl-carousel owl-theme sidebar_slider_vid">

                                    <!-- Newest Videos Slider Item -->
                                    <div class="owl-item">

                                        <!-- Newest Videos Post -->
                                        <div class="side_post">
                                            <a href="./post">
                                                <div class="d-flex flex-row align-items-xl-center align-items-start justify-content-start">
                                                    <div class="side_post_image">
                                                        <div>
                                                            <img src="zend/public/images/vid_1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="side_post_content">
                                                        <div class="side_post_title">How Did van Gogh’s Turbulent Mind</div>
                                                        <small class="post_meta">Katy Liu
                                                            <span>Sep 29</span>
                                                        </small>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>

                                    <!-- Newest Videos Slider Item -->
                                    <div class="owl-item">

                                        <!-- Newest Videos Post -->
                                        <div class="side_post">
                                            <a href="./post">
                                                <div class="d-flex flex-row align-items-xl-center align-items-start justify-content-start">
                                                    <div class="side_post_image">
                                                        <div>
                                                            <img src="zend/public/images/vid_4.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="side_post_content">
                                                        <div class="side_post_title">How Did van Gogh’s Turbulent Mind</div>
                                                        <small class="post_meta">Katy Liu
                                                            <span>Sep 29</span>
                                                        </small>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>

                                    </div>

                                    <!-- Newest Videos Slider Item -->
                                    <div class="owl-item">

                                        <!-- Newest Videos Post -->
                                        <div class="side_post">
                                            <a href="./post">
                                                <div class="d-flex flex-row align-items-xl-center align-items-start justify-content-start">
                                                    <div class="side_post_image">
                                                        <div>
                                                            <img src="zend/public/images/vid_1.jpg" alt="">
                                                        </div>
                                                    </div>
                                                    <div class="side_post_content">
                                                        <div class="side_post_title">How Did van Gogh’s Turbulent Mind</div>
                                                        <small class="post_meta">Katy Liu
                                                            <span>Sep 29</span>
                                                        </small>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>