<section class="site-section py-lg">
	<div class="container">

		<div class="row blog-entries">
			<div class="col-md-12 col-lg-8 main-content">
				<h1 class="mb-4"><?php echo $posts->title ?></h1>
				<div class="post-meta">
					<span class="category">Food</span>
					<span class="mr-2">March 15, 2018 </span> &bullet;
					<span class="ml-2">
						<span class="fa fa-comments"></span> 3</span>
				</div>
				<div class="post-content-body">
					<!-- POST CONTENT -->
					<img class="img-thumbnail" src="<?php echo $posts->post_image ?>" alt="Image placeholder">
					
					<!-- <?php echo $posts->content ?> -->
					<?php
					$cont = explode("\n", $posts->content);
					$arrlength = count($cont);
					for($x = 0; $x < $arrlength; $x++) {
						echo "<p>".$cont[$x]."</p>";
						echo "<br>";
					}
					?>
				</div>

				<div class="pt-5">
					<p>Categories:
						<a href="#">Food</a>,
						<a href="#">Travel</a> Tags:
						<a href="#">#manila</a>,
						<a href="#">#asia</a>
					</p>
				</div>


				<div class="pt-5">
					<h3 class="mb-5">Comments</h3>
					<ul class="comment-list">
						<li class="comment">
							<div class="vcard">
								<img src="../../public/images/person_1.jpg" alt="Image placeholder">
							</div>
							<div class="comment-body">
								<h3>Jean Doe</h3>
								<div class="meta">January 9, 2018 at 2:21pm</div>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae
									autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
								<p>
									<a href="#" class="reply">Reply</a>
								</p>
							</div>
						</li>
					</ul>
					<!-- END comment-list -->

					<div class="comment-form-wrap pt-5">
						<h3 class="mb-5">Leave a comment</h3>
						<form action="#" class="p-5 bg-light">
							<div class="form-group">
								<label for="name">Name *</label>
								<input type="text" class="form-control" id="name">
							</div>
							<div class="form-group">
								<label for="email">Email *</label>
								<input type="email" class="form-control" id="email">
							</div>
							<div class="form-group">
								<label for="website">Website</label>
								<input type="url" class="form-control" id="website">
							</div>

							<div class="form-group">
								<label for="message">Message</label>
								<textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
							</div>
							<div class="form-group">
								<input type="submit" value="Post Comment" class="btn btn-primary">
							</div>

						</form>
					</div>
				</div>

			</div>

			<!-- END main-content -->

			<div class="col-md-12 col-lg-4 sidebar">
				<div class="sidebar-box search-form-wrap">
					<form action="#" class="search-form">
						<div class="form-group">
							<span class="icon fa fa-search"></span>
							<input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
						</div>
					</form>
				</div>
				<!-- END sidebar-box -->
				<div class="sidebar-box">
					<div class="bio text-center">
						<img src="../../public/images/person_1.jpg" alt="Image Placeholder" class="img-fluid">
						<div class="bio-body">
							<h2>Meagan Smith</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem facilis sunt repellendus excepturi beatae
								porro debitis voluptate nulla quo veniam fuga sit molestias minus.</p>
							<p>
								<a href="#" class="btn btn-primary btn-sm">Read my bio</a>
							</p>
							<p class="social">
								<a href="#" class="p-2">
									<span class="fa fa-facebook"></span>
								</a>
								<a href="#" class="p-2">
									<span class="fa fa-twitter"></span>
								</a>
								<a href="#" class="p-2">
									<span class="fa fa-instagram"></span>
								</a>
								<a href="#" class="p-2">
									<span class="fa fa-youtube-play"></span>
								</a>
							</p>
						</div>
					</div>
				</div>
				<!-- END sidebar-box -->
				<div class="sidebar-box">
					<h3 class="heading">Popular Posts</h3>
					<div class="post-entry-sidebar">
						<ul>
							<li>
								<a href="">
									<img src="../public/images/img_1.jpg" alt="Image placeholder" class="mr-4">
									<div class="text">
										<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
										<div class="post-meta">
											<span class="mr-2">March 15, 2018 </span> &bullet;
											<span class="ml-2">
												<span class="fa fa-comments"></span> 3</span>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!-- END sidebar-box -->

				<div class="sidebar-box">
					<h3 class="heading">Categories</h3>
					<ul class="categories">
						<li>
							<a href="#">Courses
								<span>(12)</span>
							</a>
						</li>
						<li>
							<a href="#">News
								<span>(22)</span>
							</a>
						</li>
						<li>
							<a href="#">Design
								<span>(37)</span>
							</a>
						</li>
						<li>
							<a href="#">HTML
								<span>(42)</span>
							</a>
						</li>
						<li>
							<a href="#">Web Development
								<span>(14)</span>
							</a>
						</li>
					</ul>
				</div>
				<!-- END sidebar-box -->

				<div class="sidebar-box">
					<h3 class="heading">Tags</h3>
					<ul class="tags">
						<li>
							<a href="#">Travel</a>
						</li>
						<li>
							<a href="#">Adventure</a>
						</li>
						<li>
							<a href="#">Food</a>
						</li>
						<li>
							<a href="#">Lifestyle</a>
						</li>
						<li>
							<a href="#">Business</a>
						</li>
						<li>
							<a href="#">Freelancing</a>
						</li>
						<li>
							<a href="#">Travel</a>
						</li>
						<li>
							<a href="#">Adventure</a>
						</li>
						<li>
							<a href="#">Food</a>
						</li>
						<li>
							<a href="#">Lifestyle</a>
						</li>
						<li>
							<a href="#">Business</a>
						</li>
						<li>
							<a href="#">Freelancing</a>
						</li>
					</ul>
				</div>
			</div>
			<!-- END sidebar -->

		</div>
	</div>
</section>